import { useState, type PointerEvent } from 'react'
import { ArrowRight, ArrowUpRight, AudioLines, Bot, Braces, Cloud, Code2, Cpu, Lightbulb, Mic, Workflow } from 'lucide-react'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { buttonVariants } from '@/components/ui/button'
import { Reveal } from './motion'
import { MagicCard } from '@/components/ui/magic-card'

const services = [
  { icon: Bot, title: 'AI & Generative AI', tag: 'INTELLIGENCE, APPLIED', description: 'AI-powered applications, intelligent assistants, RAG systems, LLM integrations and custom GenAI solutions.', details: 'Bring intelligence into the tools your team already uses. We design grounded, purpose-built AI experiences with clear evaluation criteria, human oversight, and secure access to your business knowledge.', capabilities: ['Knowledge-grounded AI assistants', 'Retrieval-augmented generation', 'LLM integration and evaluation'] },
  { icon: Code2, title: 'Software Development', tag: 'BUILT FOR YOUR BUSINESS', description: 'Modern web, mobile and custom business applications built for performance and scalability.', details: 'From an early-stage product to a business-critical platform, we translate your requirements into intuitive experiences and maintainable software. Every decision starts with the people who will use it.', capabilities: ['Custom web and mobile applications', 'SaaS and internal platforms', 'API design and development'] },
  { icon: Workflow, title: 'Automation & RPA', tag: 'LESS MANUAL. MORE MEANINGFUL.', description: 'Automate repetitive workflows, business processes and operations to save time and reduce manual work.', details: 'Give your team time back. We map repetitive processes, identify the right opportunities for automation, and connect your systems with reliable workflows and visible exception handling.', capabilities: ['Business process automation', 'System-to-system workflows', 'Human-in-the-loop approvals'] },
  { icon: AudioLines, title: 'AI Call Quality Analysis', tag: 'EVERY CONVERSATION COUNTS', description: 'Analyze conversations with AI to identify quality, compliance, sentiment and actionable insights.', details: 'Turn conversations into useful feedback. Evaluate calls against your own quality standards, surface coaching opportunities, and review flagged moments with the original conversation in context.', capabilities: ['Conversation transcription and analysis', 'Configurable quality scorecards', 'Sentiment and compliance signals'] },
  { icon: Mic, title: 'Meeting Intelligence', tag: 'TURN TALK INTO ACTION', description: 'Record, transcribe, summarize and extract actionable insights from meetings.', details: 'Keep the conversation moving without losing the details. With appropriate recording consent, meeting intelligence can capture decisions, organize key points, and turn follow-ups into clear action items.', capabilities: ['Speaker-aware meeting transcripts', 'Summaries and decision tracking', 'Action items and tool integrations'] },
  { icon: Cloud, title: 'Cloud & Integrations', tag: 'CONNECTED BY DESIGN', description: 'Connect systems, APIs and cloud infrastructure to create scalable digital ecosystems.', details: 'Build a dependable foundation for your product. We connect the services your business depends on and design cloud infrastructure around security, observability, and sustainable growth.', capabilities: ['Cloud architecture and deployment', 'Third-party API integrations', 'Monitoring and delivery pipelines'] },
]

export function Intro() {
  return <section id="intro" className="intro-section section-border"><div className="container"><Reveal className="intro-layout"><div><span className="eyebrow"><span />YOUR IDEAS. OUR ENGINEERING.</span><h2>Technology built<br />{' '}around <span className="muted-heading">your business.</span></h2></div><div className="intro-right"><p>From intelligent automation to custom software platforms, we turn complex business challenges into scalable digital solutions.</p><a href="#about" className="text-link">A little about us <ArrowUpRight size={16} /></a></div></Reveal><div className="expertise-row">{[{ icon: Cpu, title: 'AI & Automation', sub: 'Make intelligence your advantage.' }, { icon: Braces, title: 'Custom Software', sub: 'Purpose-built. Never one-size-fits-all.' }, { icon: Lightbulb, title: 'Digital Innovation', sub: 'Move your next big idea forward.' }].map(({ icon: Icon, title, sub }, i) => <Reveal key={title} delay={i * 0.08}><div className="expertise-item"><span className="expertise-icon"><Icon size={22} strokeWidth={1.6} /></span><div><h3>{title}</h3><p>{sub}</p></div><ArrowUpRight size={18} className="expertise-arrow" /></div></Reveal>)}</div></div></section>
}

export function Services() {
  const [active, setActive] = useState<number | null>(null)
  function moveGlow(event: PointerEvent<HTMLButtonElement>) {
    if (event.pointerType !== 'mouse') return
    const rect = event.currentTarget.getBoundingClientRect()
    event.currentTarget.style.setProperty('--mouse-x', `${event.clientX - rect.left}px`)
    event.currentTarget.style.setProperty('--mouse-y', `${event.clientY - rect.top}px`)
  }
  return <section id="services" className="services-section section-space"><div className="container"><Reveal className="section-heading"><div><span className="eyebrow"><span />WHAT WE DO</span><h2>What we <span className="serif-word">build.</span></h2></div><p>Technology solutions designed to solve<br className="desktop-break" /> real business problems.</p></Reveal><div className="services-grid">{services.map((service, i) => <Reveal key={service.title} delay={(i % 3) * 0.07} className="h-full"><MagicCard className="service-magic" gradientSize={260} gradientColor="#e3efff" gradientOpacity={0.9} gradientFrom="#2167e8" gradientTo="#17b6be"><button className="service-card" onPointerMove={moveGlow} onClick={() => setActive(i)} aria-label={`Explore ${service.title}`}><div className="service-card-top"><span className="service-icon"><service.icon size={25} strokeWidth={1.6} /></span><span className="service-index">0{i + 1}</span></div><h3>{service.title}</h3><p>{service.description}</p><div className="service-card-bottom"><span>{service.tag}</span><span className="service-arrow"><ArrowUpRight size={18} /></span></div></button></MagicCard></Reveal>)}</div><Reveal className="services-note"><span>Have a challenge that doesn&apos;t fit a box?</span><a href="#contact" className="text-link">Let&apos;s figure it out together <ArrowRight size={15} /></a></Reveal></div><Dialog open={active !== null} onOpenChange={open => { if (!open) setActive(null) }}><DialogContent className="service-dialog sm:max-w-xl">{active !== null && <><DialogHeader><span className="eyebrow">HOW WE CAN HELP</span><DialogTitle>{services[active].title}</DialogTitle><DialogDescription>{services[active].description}</DialogDescription></DialogHeader><p className="dialog-copy">{services[active].details}</p><ul className="capability-list">{services[active].capabilities.map(item => <li key={item}><ArrowUpRight size={16} />{item}</li>)}</ul><a href="#contact" onClick={() => setActive(null)} className={buttonVariants({ variant: 'brand', size: 'hero' })}>Let&apos;s talk about your idea <ArrowUpRight data-icon="inline-end" /></a></>}</DialogContent></Dialog></section>
}
